name: tf5
channels:
    - conda-forge
    - defaults
dependencies:    
    - pandas
    - matplotlib
    - tensorflow-gpu
    - tensorboard
    - cudtoolkit
    - cudtoolkit-dev
    - numba
    - numpy
    - h5py
    - memory_profiler
    - pympler
    - scipy
    - lz4
    - pip
    - pip:
        - tensorboard-plugin-profile
        - bmtk

