"""Render the study's figures to PDF and its numbers to a LaTeX macro file.

Run before compiling report.tex.  Everything it writes comes from :mod:`_study`,
so the report can never quote a number the notebook does not also show.
"""
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import matplotlib
matplotlib.use("Agg")

import numpy as np

import _figures as F
import _simulation as S
import _study

HERE = os.path.dirname(os.path.abspath(__file__))
FIGURES = os.path.join(HERE, "figures")


def _macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def _si(x, digits=1):
    """A number in LaTeX scientific notation, e.g. 6.4\\times10^{-2}."""
    if x == 0:
        return "0"
    exponent = int(np.floor(np.log10(abs(x))))
    mantissa = x / 10.0 ** exponent
    if round(abs(mantissa), digits) >= 10.0:      # 9.96 -> 1.0e+1, not 10.0e0
        mantissa, exponent = mantissa / 10.0, exponent + 1
    return rf"{mantissa:.{digits}f}\times 10^{{{exponent}}}"


def main():
    os.makedirs(FIGURES, exist_ok=True)
    F.use_style()
    r = _study.run_all()
    p = r["p"]

    figures = {
        "timescales": F.timescales(p["tau_m"], S.TAU_SYN, S.DT),
        "convergence": F.convergence(r["convergence"]["substeps"],
                                     r["convergence"]["errors"],
                                     r["convergence"]["exact"],
                                     r["convergence"]["legacy"]),
        "errors": F.error_bars(r["errors"]),
        "psp": F.psp(r["psp"]["ms"], r["psp"]["truth"], r["psp"]["traces"],
                     r["psp"]["peaks"]),
        "spikes": F.spike_fidelity(r["closed_loop"]["rows"],
                                   r["closed_loop"]["reference"],
                                   r["closed_loop"]["by_scheme"],
                                   slice(300, 460)),
        "precision": F.precision_ablation(r["precision"]["rows"],
                                          r["precision"]["euler_fp16"]),
    }
    for name, figure in figures.items():
        path = os.path.join(FIGURES, f"{name}.pdf")
        figure.savefig(path, bbox_inches="tight")
        print("wrote", path)

    # Every number the report quotes, as a macro, so the text cannot drift.
    def row(case, scheme):
        return next(x for x in r["errors"]
                    if x["case"] == case and x["scheme"] == scheme)

    def closed(scheme, precision):
        return next(x for x in r["closed_loop"]["rows"]
                    if x["scheme"] == scheme and x["precision"] == precision)

    sub_euler, sub_exact = row("subthreshold", "euler"), row("subthreshold", "exact")
    spk_euler, spk_exact = row("spiking (~10 Hz)", "euler"), row("spiking (~10 Hz)", "exact")
    text = [
        "% Generated by export_figures.py - do not edit.\n",
        _macro("nCellTypes", p["tau_m"].size),
        _macro("tauMemMin", f"{p['tau_m'].min():.1f}"),
        _macro("tauMemMed", f"{np.median(p['tau_m']):.1f}"),
        _macro("tauMemMax", f"{p['tau_m'].max():.1f}"),
        _macro("tauSynFast", f"{S.TAU_SYN[0]:.2f}"),
        _macro("tauSynSlow", f"{S.TAU_SYN[-1]:.2f}"),
        _macro("nBasis", S.TAU_SYN.size),
        # A bound, not the measured value: the last digits of a matrix
        # exponential depend on the LAPACK build, and only the order matters.
        _macro("expmBound", "10^{%d}" % int(np.ceil(np.log10(
            r["identity"]["worst"])))),
        _macro("eulerErrSub", _si(sub_euler["fp64"])),
        _macro("exactErrSub", _si(sub_exact["fp64"])),
        _macro("eulerErrSpk", _si(spk_euler["fp64"])),
        _macro("exactErrSpk", _si(spk_exact["fp64"])),
        _macro("eulerErrSpkHalf", _si(spk_euler["fp16"])),
        _macro("exactErrSpkHalf", _si(spk_exact["fp16"])),
        _macro("exactErrSpkHalfState", _si(spk_exact["fp16_state"])),
        _macro("eulerErrSpkHalfState", _si(spk_euler["fp16_state"])),
        _macro("constantPenalty",
               f"{spk_exact['fp16'] / spk_exact['fp16_state']:.1f}"),
        _macro("gainSpk", f"{spk_euler['fp64'] / spk_exact['fp64']:,.0f}".replace(",", r"\,")),
        _macro("gainSub", f"{sub_euler['fp64'] / sub_exact['fp64']:,.0f}".replace(",", r"\,")),
        _macro("gainSpkHalf", f"{spk_euler['fp16'] / spk_exact['fp16']:.0f}"),
        _macro("matchEuler", f"{closed('euler', 'float64')['match'] * 100:.1f}"),
        _macro("matchExact", f"{closed('exact', 'float64')['match'] * 100:.1f}"),
        _macro("matchExactHalf", f"{closed('exact', 'float16')['match'] * 100:.1f}"),
        _macro("matchEulerHalf", f"{closed('euler', 'float16')['match'] * 100:.1f}"),
        *[_macro(f"within{scheme.capitalize()}{tag}",
                 f"{closed(scheme, precision)['within_one'] * 100:.1f}")
          for scheme in ("euler", "exact")
          for precision, tag in (("float64", ""), ("float16", "Half"), ("mixed", "Mixed"))],
        _macro("matchEulerMixed", f"{closed('euler', 'mixed')['match'] * 100:.1f}"),
        _macro("matchExactMixed", f"{closed('exact', 'mixed')['match'] * 100:.1f}"),
        _macro("eulerErrSpkMixed", _si(spk_euler["mixed"])),
        _macro("exactErrSpkMixed", _si(spk_exact["mixed"])),
        _macro("rateErrEuler", f"{closed('euler', 'float64')['rate_err'] * 100:.1f}"),
        _macro("refRate", f"{r['closed_loop']['rate']:.1f}"),
        _macro("halfMissed", r["closed_loop"]["half_missed"]),
        _macro("halfOneOff", f"{r['closed_loop']['half_one_off'] * 100:.0f}"),
        _macro("halfWithinOne", f"{r['closed_loop']['half_within_one'] * 100:.0f}"),
        _macro("closedSubsteps", _study.CLOSED_SUBSTEPS),
        _macro("closedSubstepsCoarse", _study.CLOSED_SUBSTEPS // 8),
        _macro("matchExactCoarse", f"{r['closed_loop']['coarse_match'] * 100:.1f}"),
        # First order, so the reference's own voltage error is Euler's / M.
        _macro("closedRefErr", _si(spk_euler["fp64"] / _study.CLOSED_SUBSTEPS)),
        _macro("refSpikes", f"{r['closed_loop']['n_spikes']:,}".replace(",", r"\,")),
        _macro("pspUnderestimate", f"{r['psp']['underestimate'] * 100:.1f}"),
        _macro("pspTauM", f"{r['psp']['tau_m']:.1f}"),
    ]
    # Euler's float64 error with only one of its two approximations left.
    for case, tag in (("subthreshold", "Sub"), ("spiking", "Spk")):
        d = r["decomposition"][case]
        text += [_macro(f"hybrid{tag}Events", _si(d["events_only"])),
                 _macro(f"hybrid{tag}Current", _si(d["current_only"]))]

    # Numbers the prose quotes, derived rather than typed.
    import numpy as _np
    from v1_model_utils.glif_propagators import membrane_coefficients
    exact = membrane_coefficients(p["tau_m"], p["g"], S.TAU_SYN, p["k"],
                                  p["asc_amps"], S.DT)
    decay = _np.exp(-S.DT / p["tau_m"])
    text += [
        # How far the end-of-step reset sits from the correct one.
        _macro("resetTimingError",
               f"{(1 - decay)[_np.argsort(p['tau_m'])[len(decay) // 2]]:.2f}"),
        # How large the ASC-injection constant gets next to the reset.
        _macro("ascFracOfReset", f"{100 * _np.abs(
            exact['asc_spike_factor'] / exact['reset_coeff']).max():.0f}"),
        _macro("eulerErrSpkPct", f"{100 * spk_euler['fp64']:.0f}"),
    ]
    # Every constant the kernel holds: syn_decay, psc_initial, psc_factor and
    # psc_rise_factor at R each, asc_factor / asc_decay / asc_amps at 2 each,
    # and decay / reset_coeff / asc_spike_factor at 1 each - shared across the
    # batch and the sequence, so widening them is a fixed cost.
    words = 4 * S.TAU_SYN.size + 3 * 2 + 3
    if r["benchmark"]:
        n_big = max(x["n"] for x in r["benchmark"]["rows"])
        text += [_macro("constantWidenMB", f"{words * n_big * 2 / 1e6:.0f}"),
                 _macro("constantWords", words)]

    # Two defects the rewrite exposed, quantified rather than asserted.
    import tensorflow as _tf
    k = p["k"]
    k16 = _tf.cast(k, _tf.float16)
    round_trip = _tf.nn.sigmoid(
        _tf.cast(_tf.math.log(k16 / (1 - k16)), _tf.float16)).numpy().astype(np.float64)
    steps = np.round(3.0 / k)                       # three ASC time constants
    text += [
        _macro("ascKError", _si(np.abs(round_trip / k - 1).max())),
        _macro("ascAmplitudeError",
               f"{100 * np.abs(np.exp(-round_trip) ** steps
                               / np.exp(-k) ** steps - 1).max():.1f}"),
        _macro("tRefMin", int(p["t_ref_steps"].min())),
        _macro("tRefMax", int(p["t_ref_steps"].max())),
    ]

    prec = {row["half"]: row for row in r["precision"]["rows"]}
    wide, narrow = prec["psc, rise"], prec["v, psc, rise, asc"]
    text += [
        _macro("precisionGain", f"{narrow['err'] / wide['err']:.0f}"),
        _macro("precisionBytes",
               f"{100 * (wide['bytes'] - narrow['bytes']) / narrow['bytes']:.0f}"),
        _macro("exactErrSubHalf", _si(sub_exact["fp16"])),
        _macro("exactErrSubHalfState", _si(sub_exact["fp16_state"])),
        _macro("eulerErrSubHalf", _si(sub_euler["fp16"])),
        _macro("eulerErrSubHalfState", _si(sub_euler["fp16_state"])),
    ]
    if r["benchmark"]:
        b = r["benchmark"]
        biggest = max(b["rows"], key=lambda x: x["n"] * x["batch"]
                      if x["dtype"] == "fp16" else -1)
        text += [
            _macro("kernelRatio", f"{b['fp16_mean']:.2f}"),
            _macro("kernelRatioMin", f"{b['fp16_min']:.2f}"),
            _macro("kernelRatioMax", f"{b['fp16_max']:.2f}"),
            _macro("kernelNeurons", f"{biggest['n']:,}".replace(",", r"\,")),
            _macro("kernelBatch", biggest["batch"]),
            _macro("kernelConstantMB", f"{biggest['extra_constant_MB']:.1f}"),
        ]
    # The benchmark table, generated whole: LaTeX's \input misbehaves inside a
    # tabular, and this keeps the numbers and their layout in one place.
    if r["benchmark"]:
        rows = "".join(
            f"    {x['n']:,} & {x['batch']} & \\code{{{x['dtype']}}} & "
            f"{x['legacy_fwd']:.1f} & {x['new_fwd']:.1f} & "
            f"{x['legacy_bwd']:.1f} & {x['new_bwd']:.1f} & "
            f"{x['ratio']:.2f}$\\times$ \\\\\n".replace(",", "\\,")
            for x in r["benchmark"]["rows"])
        table = os.path.join(HERE, "benchtable.tex")
        with open(table, "w") as handle:
            handle.write(
                "% Generated by export_figures.py - do not edit.\n"
                "\\begin{table}[t]\n  \\centering\n"
                "  \\caption[Kernel timings]{%\n"
                "    Per-timestep cost of the fused GLIF state kernels, in\n"
                "    microseconds, on an NVIDIA RTX PRO 6000. Each timing chains\n"
                "    64 state transitions inside one \\code{tf.function}.\n"
                "    \\code{fp16} is the configuration used for training.}\n"
                "  \\label{tab:bench}\n"
                "  \\begin{tabular}{rrlrrrrr}\n    \\toprule\n"
                "    & & & \\multicolumn{2}{c}{forward}"
                " & \\multicolumn{2}{c}{backward} & \\\\\n"
                "    \\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\n"
                "    Neurons & Batch & dtype & Euler & exact & Euler & exact"
                " & Ratio \\\\\n    \\midrule\n"
                + rows +
                "    \\bottomrule\n  \\end{tabular}\n\\end{table}\n")
        print("wrote", table)

    if r["gradients"]:
        g = r["gradients"]
        text += [
            _macro("gradWorst", _si(g["overall"])),
            _macro("gradWorstPrevZ", _si(max(
                b["prev_z"]["rel_err"] for b in g["blocks"].values()))),
            _macro("gradBackends", len({k.split("/")[0] for k in g["blocks"]})),
        ]

    path = os.path.join(HERE, "numbers.tex")
    with open(path, "w") as handle:
        handle.writelines(text)
    print("wrote", path, f"({len(text) - 1} macros)")


if __name__ == "__main__":
    main()
